language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.0
    - android-23
    - android-24

env:
- GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"

script:
 - ./gradlew tracklytics-runtime:check